package com.example.dailyuacm.ui.navigation

object RoutesNavigationDrawer {
    const val HOME_NAVIGATION_ROUTE_NAME = "HOME_SCREEN"
    const val AGENDA_NAVIGATION_ROUTE_NAME = "AGENDA_SCREEN"
    const val CALENDAR_NAVIGATION_ROUTE_NAME = "CALENDAR_SCREEN"
    const val USER_NAVIGATION_ROUTE_NAME = "USER_SCREEN"
    const val TEACHER_NAVIGATION_ROUTE_NAME = "TEACHER_SCREEN"
    const val RATING_NAVIGATION_ROUTE_NAME = "RATING_SCREEN"
    const val SETTINGS_NAVIGATION_ROUTE_NAME = "SETTINGS_SCREEN"
    const val CURSES_NAVIGATION_ROUTE_NAME = "CURSES_SCREEN"
    const val PROFESSION_NAVIGATION_ROUTE_NAME = "PROFESSION_SCREEN"
    const val TERMS_AND_CONDITIONS_NAVIGATION_ROUTE_NAME = "TERMS_AND_CONDITIONS_SCREEN"
    const val HELP_AND_QUESTION_NAVIGATION_ROUTE_NAME = "HELP_AND_QUESTION_SCREEN"
}
object RoutesNavigationLoginAndRegister {
    const val USER_LOGIN = "LOGIN_SCREEN"
    const val REGISTER_LOGIN = "LOGIN_SCREEN"
}